Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -74,7 +74,7 @@ sleep 1  # Add a 1-second delay
 # Step 5: Create swap space
 if ! [ "$(sudo swapon -s)" ]; then
   echo "Creating swap space..."
-  sudo mkdir /swap && sudo fallocate -l 8G /swap/swapfile && sudo chmod 600 /swap/swapfile || { echo "Failed to create swap space! Exiting..."; exit_message; exit 1; }
+  sudo mkdir /swap && sudo fallocate -l 10G /swap/swapfile && sudo chmod 600 /swap/swapfile || { echo "Failed to create swap space! Exiting..."; exit_message; exit 1; }
   sudo mkswap /swap/swapfile && sudo swapon /swap/swapfile || { echo "Failed to set up swap space! Exiting..."; exit_message; exit 1; }
   sudo bash -c 'echo "/swap/swapfile swap swap defaults 0 0" >> /etc/fstab' || { echo "Failed to update /etc/fstab! Exiting..."; exit_message; exit 1; }
 fi
